name: CI/CD to Minikube

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker to use Minikube
        run: |
          eval $(minikube docker-env)

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/

      - name: Check rollout
        run: |
          kubectl rollout status deployment/flask-app

